name: env_group7
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.6.0
  - scipy=1.13.1
  - matplotlib-inline=0.1.7
  - ipykernel=6.29.5
  - streamlit=1.40.2
  - tqdm=4.67.1
  - sqlalchemy=2.0.36
  - cryptography=44.0.0
  - cffi=1.17.1
  - pywin32=307
  - pip
  - pip:
      - spacy==3.8.3
      - aiofiles==24.1.0
      - aiohttp==3.9.5
      - aiosignal==1.3.2
      - altair==5.5.0
      - huggingface-hub==0.27.0
      - langchain==0.3.9
      - langchain-community==0.3.4
      - langchain-core==0.3.28
      - langchain-openai==0.2.10
      - langchain-pinecone==0.2.0
      - langchain-text-splitters==0.3.4
      - pinecone-client==5.0.1
      - transformers==4.46.3
      - sentence-transformers==3.3.1
      - tiktoken==0.8.0
      - uvicorn==0.34.0
      - openai==1.55.3
      - streamlit-option-menu
      - pdfplumber
      - selenium
      - semantic-router
